version: "3.1"

services:
  kavanest-skippy:
    container_name: kavanest-skippy
    image: kavanest-skippy
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - proxynet
    environment:
      - ENVIRONMENT=docker
      - MQTT_DOCKER=mqtt://mosquitto
      - MONGO_DOCKER=mongodb://kavanest-mongo:27017

networks:
  proxynet:
    name: kavanest-devnet
