## Need a build stage to compile the typescript
## Cant get the build to work with base url. Try counter (1)

## Build stage
# FROM node:16 as build
FROM arm64v8/node:22-alpine AS build

COPY . .

RUN yarn install
RUN yarn build


## Deploy stage
FROM arm64v8/node:22-alpine
# FROM node:16

WORKDIR /usr/src/app

COPY --from=build ./dist ./

COPY package*.json ./
COPY tsconfig.json ./

ENV NODE_ENV=production
RUN yarn install

EXPOSE 1883
EXPOSE 9001

CMD ["node","index.js"]
