version: "3.1"

services:
  kavanest-skippy:
    container_name: kavanest-skippy
    image: kavanest-skippy
    build:
      context: .
      dockerfile: Dockerfile.argo

    networks:
      - proxynet
    environment:
      - API=http://api.kavanet.io
      - MQTT=mqtt://kavanet.io

networks:
  proxynet:
    name: kavanest-devnet
    external: true
