# Use Node version 14
FROM arm64v8/node

# Create app directory within container
WORKDIR /usr/src/app

# Install app dependencies
# A wild card is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY tsconfig.json ./

# Prevents unnecessary packages from being installed
ENV NODE_ENV=production
RUN npm install

# Copy across source folder
COPY ./dist ./

EXPOSE 1883
EXPOSE 9001
# CMD ["npm", "start"]
CMD ["node","index.js"]