name: kavanest-controller

namespace: kavanest
env:
  APP_VERSION: e33ada997a0dab077386e9d902d1342834735180

deployment:
  - name: kavanest-controller
    image: invisibug/kavanest-controller
    env:
      - name: API
        value: http://kavanest-api # Alows the controller to run even when the internet is down
      - name: MQTT
        value: mqtt://kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
