name: kavanest-controller

namespace: kavanest
env:
  APP_VERSION: 654a244aa939e9d621cb55d1c171271b309280d2

deployment:
  - name: kavanest-controller
    image: invisibug/kavanest-controller
    env:
    - name: API
      value: http://kavanest-api # Alows the controller to run even when the internet is down
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
