name: kavanest-controller

namespace: kavanest
env:
  APP_VERSION: 656685ab2ce6abd743156e57bb37a52d81da7bf0

deployment:
  - name: kavanest-controller
    image: invisibug/kavanest-controller
    env:
      - name: API
        value: http://kavanest-api # Alows the controller to run even when the internet is down
      - name: MQTT
        value: mqtt://kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
