name: kavanest-skippy

namespace: kavanest
env:
  APP_VERSION: 0c3beb244ea738360257de52c1816704e7752e76

deployment:
  - name: kavanest-skippy
    image: invisibug/kavanest-skippy
    env:
    - name: API
      value: http://kavanest-api # Alows the controller to run even when the internet is down
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
