name: kavanest-controller

namespace: kavanest
env:
  APP_VERSION: 41a47dcac8802515a123a60804fa704f0bf8599d

deployment:
  - name: kavanest-controller
    image: invisibug/kavanest-controller
    env:
    - name: API
      value: http://kavanest-api # Alows the controller to run even when the internet is down
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
