name: kavanest-controller

namespace: kavanest
env:
  APP_VERSION: 34d041c2b682317179fe80022c7717f01b5e03ac

deployment:
  - name: kavanest-controller
    image: invisibug/kavanest-controller
    env:
      - name: API
        value: http://kavanest-api # Alows the controller to run even when the internet is down
      - name: MQTT
        value: mqtt://kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
