name: kavanest-test-skippy

namespace: kavanest-test
env:
  APP_VERSION: ded07a4950296ca9bd506fb73661e278394b10a2

deployment:
  - name: kavanest-test-skippy
    image: 192.168.1.61:5000/kavanest-skippy:test
    env:
      - name: API
        value: http://test.api.kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 1000m
