name: kavanest-test-skippy

namespace: kavanest-test

deployment:
  - name: kavanest-test-skippy
    image: 192.168.1.61:5000/kavanest-skippy
    env:
    - name: API
      value: http://test.api.kavanet.io
