name: kavanest-test-controller

namespace: kavanest-test
env:
  APP_VERSION: aa7e63b7aad587688068b39176e78e94d39ca550

deployment:
  - name: kavanest-test-controller
    image: invisibug/kavanest-test-controller
    env:
      - name: API
        value: http://test.api.kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 100m
