name: kavanest-test-controller

namespace: kavanest-test
env:
  APP_VERSION: d7bb8d788c504c1981249382a3804d16cb58154f

deployment:
  - name: kavanest-test-controller
    image: invisibug/kavanest-test-controller
    env:
      - name: API
        value: http://test.api.kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 100m
