name: kavanest-test-skippy

namespace: kavanest-test
env:
  APP_VERSION: 5eb9c93eae51e4c2c0c1300f9410a746cc12b84a

deployment:
  - name: kavanest-test-skippy
    image: 192.168.1.61:5000/kavanest-skippy:test
    env:
      - name: API
        value: http://test.api.kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 100m
