name: kavanest-test-controller

namespace: kavanest-test
env:
  APP_VERSION: a8aaae2269921c9a126d4183b93e6f62e31819fb

deployment:
  - name: kavanest-test-controller
    image: invisibug/kavanest-test-controller
    env:
      - name: API
        value: http://test.api.kavanet.io
      - name: MQTT
        value: mqtt://kavanet.io
    # resources:
    #   memory: 100Mi
    #   cpu: 100m
