name: CD

on:
  push:
    branches:
      - test-release

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_KEY: ${{ secrets.DOCKERHUB_KEY }}
  IMAGE_NAME: kavanest-test-controller
  DOCKER_DEFAULT_PLATFORM: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_KEY }}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -f ./Dockerfile.argo -t ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  tag-branch:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update values.yaml
      run: |
        cd helm
        sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' ./values/test.yaml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ./values/test.yaml
        git commit -m "Update values.yaml"
        git push


  sync-test:
    needs: tag-branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge test-release -> test
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: fast-forward test
          from_branch: test-release
          target_branch: test
          github_token: ${{ secrets.ACCESS_TOKEN }}

  sync-dev:
    needs: sync-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge test-release -> test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: test
          message: fast-forward dev
          target_branch: dev
          github_token: ${{ secrets.ACCESS_TOKEN }}
